#!/usr/bin/env python3
"""Manual, quarterly cohort selection for hf-text-generation.

NEVER run this on a cron — cohort membership is a human decision, frozen in a
dated vintage file and reviewed in a commit.

    python scripts/select_cohort.py --date 2026-10-01 \
        --top-n 200 --floor 10000 --new-since 2026-07-01 [--emit-registry] [--dry-run]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import requests

from snapshotter.capture import contact_from_env, user_agent
from snapshotter.cohort import CohortCriteria, effective_members, select_vintage, write_vintage

REPO = Path(__file__).resolve().parents[1]
COHORT_DIR = REPO / "cohorts" / "hf-text-generation"
MEMBERS_SOURCE_ID = "hf.models.cohort-members"

CANDIDATES_URL = (
    "https://huggingface.co/api/models"
    "?pipeline_tag=text-generation&sort=downloads&direction=-1&limit=1000"
    "&expand[]=downloads&expand[]=likes&expand[]=createdAt"
)

REGISTRY_HEADER = f"""\
# GENERATED by scripts/select_cohort.py — do not hand-edit endpoints.
# One endpoint per effective cohort member (union of all vintages, dead
# members included). expect_status [200, 404]: a member's death 404s, and the
# 404 body is archived as the death record instead of failing the run.
source_id: {MEMBERS_SOURCE_ID}
status: paused
cadence: daily
schema_id: adoption-member.v1

publisher: Hugging Face
publisher_tier: first_party
destroys_own_history: true
licence: "Hub metadata via public API; see https://huggingface.co/terms-of-service"
personal_data: none
storage: git

endpoints:
"""

REGISTRY_FOOTER = """\
gates:
  expect_status: [200, 404]
  min_bytes: 10
  content_type_any: [json]
"""


def fetch_candidates() -> list[dict]:
    contact = contact_from_env()
    resp = requests.get(CANDIDATES_URL, headers={"User-Agent": user_agent(contact)}, timeout=60)
    resp.raise_for_status()
    candidates = resp.json()
    if not isinstance(candidates, list) or not candidates:
        raise SystemExit("unexpected response shape from /api/models — aborting, nothing written")
    return candidates


def emit_members_registry() -> Path:
    members = effective_members(COHORT_DIR)
    lines = [REGISTRY_HEADER]
    for entity_id in sorted(members):
        lines.append(f'  - url: "https://huggingface.co/api/models/{entity_id}"\n')
        lines.append("    delay_seconds: 2\n")
    lines.append("\n")
    lines.append(REGISTRY_FOOTER)
    path = REPO / "registry" / f"{MEMBERS_SOURCE_ID}.yml"
    path.write_text("".join(lines), encoding="utf-8")
    return path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--date", required=True, help="vintage date, YYYY-MM-DD (immutable once written)")
    ap.add_argument("--top-n", type=int, default=200)
    ap.add_argument("--floor", type=float, default=10_000, help="min downloads_30d for the established path")
    ap.add_argument("--new-since", required=True, help="createdAt cutoff for the new-entrant path, YYYY-MM-DD")
    ap.add_argument("--emit-registry", action="store_true", help=f"rebuild registry/{MEMBERS_SOURCE_ID}.yml")
    ap.add_argument("--dry-run", action="store_true", help="print the selection, write nothing")
    args = ap.parse_args()

    criteria = CohortCriteria(
        metric_key="downloads",
        created_key="createdAt",
        established_top_n=args.top_n,
        established_floor=args.floor,
        new_entrant_since=args.new_since,
    )
    candidates = fetch_candidates()
    vintage = select_vintage(candidates, criteria, selected_at=args.date)

    by_path: dict[str, int] = {}
    for member in vintage.members:
        for p in member.paths:
            by_path[p] = by_path.get(p, 0) + 1
    print(f"vintage {args.date}: {len(vintage.members)} member(s) " f"({', '.join(f'{k}={v}' for k, v in sorted(by_path.items()))})")
    for member in vintage.members:
        print(f"  {','.join(member.paths):<26} {member.entity_id}")

    if args.dry_run:
        print("dry run — nothing written")
        return 0

    path = write_vintage(COHORT_DIR, vintage)
    print(f"wrote {path.relative_to(REPO)}")
    if args.emit_registry:
        reg = emit_members_registry()
        print(f"wrote {reg.relative_to(REPO)} — starts paused; doctor it, then set active")
    return 0


if __name__ == "__main__":
    sys.exit(main())
